#ifndef _CONFIG_H__
#define _CONFIG_H__

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define CIRCLE_RADIUS 25
#define CONSTRAINT_CENTER_X (WINDOW_WIDTH/2.0)
#define CONSTRAINT_CENTER_Y (WINDOW_HEIGHT/2.0)
#define CONSTRAINT_RADIUS ((WINDOW_HEIGHT/2.0))
#define GRID_WIDTH 1
#define GRID_HEIGHT 1


#endif // _CONFIG_H__
