#ifndef _CONFIG_H__
#define _CONFIG_H__

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define CIRCLE_RADIUS 6
#define CONSTRAINT_CENTER_X 0.
#define CONSTRAINT_CENTER_Y 0.
#define CONSTRAINT_RADIUS 1.
#define GRID_WIDTH 36
#define GRID_HEIGHT 36


#endif // _CONFIG_H__
